# Sorting arrays

Ordering or sorting arrays of data is a very common numerical task.

This is easy to complete when using the `numpy.sort()` function.

## The sort method

> Syntax
<font size="4">
```python
numpy.sort(a, axis=-1, kind=None, order=None)
```
</font>

*Parameters*
* `a` : the array to sort.
* `axis` : `int` or `None`, optional. The axis along which the array will be sorted. The default is `-1`, which sorts along the last axis.
* `kind` : {‘quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’}, optional. The sorting algorithm. The default is ‘quicksort’.

Sorting is performed in ascending order.


In [1]:
import numpy as np

a = np.random.randint(10, 99, 9)
arr1 = a.reshape(3, 3)

print(arr1)

# sort
arr2 = np.sort(arr1)

print(arr2)

[[70 64 51]
 [64 41 95]
 [83 10 51]]
[[51 64 70]
 [41 64 95]
 [10 51 83]]


## Sort and flatten

To flatten the array when sorting add `axis=None` to the sort call.

In [2]:
a = np.random.randint(10, 99, 9)
arr1 = a.reshape(3, 3)

print(arr1)

# sort and flatten array
arr2 = np.sort(arr1, axis=None)

print(arr2)

[[31 54 23]
 [13 27 93]
 [15 69 56]]
[13 15 23 27 31 54 56 69 93]


## Sort Each Row

To sort each row of a 2D array in ascending order you need to specify the axis along which to sort. In this case we need to sort along axis=1.

In [3]:
a = np.random.randint(10, 99, 9)
arr1 = a.reshape(3, 3)

print(arr1)

# sort each row
arr2 = np.sort(arr1, axis=1)

print(arr2)

[[28 77 83]
 [26 84 76]
 [60 36 91]]
[[28 77 83]
 [26 76 84]
 [36 60 91]]


## Sort Each Column

This works in the same way as row sorting except that now you are sorting along axis=0.

In [4]:
a = np.random.randint(10, 99, 9)
arr1 = a.reshape(3, 3)

print(arr1)

# sort each column
arr2 = np.sort(arr1, axis=0)

print(arr2)

[[12 28 93]
 [64 67 42]
 [75 24 98]]
[[12 24 42]
 [64 28 93]
 [75 67 98]]
