<a href="https://colab.research.google.com/github/tariqzahratahdi/DataScience/blob/main/course_numpy_sorting_arrays_fr.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tri des arrays

Le tri des arrays de données est une tâche numérique très courante.

Ceci est facile à réaliser à l'aide de la fonction **`numpy.sort()`**.

## La méthode de tri

> Syntaxe
<font size = "4">
```python
numpy.sort(a, axis=-1, kind=None, order=None)
```
</font>

*Paramètres*
* `a`: l'array à trier.
* `axis`: `int` ou `None`, facultatif. L'axe sur lequel l'array sera trié. La valeur par défaut est `-1`, qui trie le long du dernier axe.
* `kind`: {`quicksort`, `mergesort`, `heapsort`, `stable`}, facultatif. L'algorithme de tri. La valeur par défaut est `quicksort`.

Le tri est effectué dans l'ordre croissant.


In [1]:
import numpy as np

a = np.random.randint(10, 99, 9)
arr1 = a.reshape(3, 3)

print(arr1)

# sort
arr2 = np.sort(arr1)

print(arr2)

[[64 52 49]
 [50 59 86]
 [12 54 35]]
[[49 52 64]
 [50 59 86]
 [12 35 54]]


## Trier et aplatir

Pour aplatir l'array lors du tri, on ajoute `axis=None` à l'appel de tri.

In [2]:
a = np.random.randint(10, 99, 9)
arr1 = a.reshape(3, 3)

print(arr1)

# sort and flatten array
arr2 = np.sort(arr1, axis=None)

print(arr2)

[[29 96 52]
 [30 89 61]
 [93 75 11]]
[11 29 30 52 61 75 89 93 96]


## Tri de chaque ligne

Pour trier chaque ligne d'un array 2D dans l'ordre croissant, on spécifie l'axe sur lequel trier. Dans ce cas, on doit trier le long de `axis=1`.

In [3]:
a = np.random.randint(10, 99, 9)
arr1 = a.reshape(3, 3)

print(arr1)

# sort each row
arr2 = np.sort(arr1, axis=1)

print(arr2)

[[18 32 91]
 [11 51 37]
 [60 11 19]]
[[18 32 91]
 [11 37 51]
 [11 19 60]]


## Tri de chaque colonne

On procède de la même manière que le tri des lignes, sauf qu'on trie le long de `axis=0`.

In [4]:
a = np.random.randint(10, 99, 9)
arr1 = a.reshape(3, 3)

print(arr1)

# trier chaque colonne
arr2 = np.sort(arr1, axis=0)

print(arr2)

[[20 59 79]
 [43 47 31]
 [43 82 48]]
[[20 47 31]
 [43 59 48]
 [43 82 79]]
