# Concaténation et Fractionnement d'un Array

# Concaténation d'un array

La fonction de concaténation de NumPy fournit une méthode pour joindre des séquences d'arrays le long d'un axe existant.

Si on a besoin de construire une matrice à partir d'un ensemble de arrays plus petits, on utilise la fonction `numpy.concatenate()`.

> Syntaxe
<font size = "4">
```python
numpy.concatenate((a1, a2, …), axis=0)
```
</font>

Le paramètre `axis` définit l'axe ou la dimension sur laquelle les arrays doivent être joints. L'axe par défaut `axis=0` joindra sur l'axe zéro.

## Concaténation des lignes

Pour concaténer deux arrays `a` et `b` le long de l'axe des lignes, on définit `axis=0`. Cela ajoutera l'array `b` en tant que nouvelle ligne sous l'array `a`.

**Exemple**



In [ ]:
import numpy as np

# 2 x 2 matrix
a = np.array([[1, 2], [3, 4]])

# 1 x 2 matrix
b = np.array([[5,6]])

# adding a new row
c = np.concatenate((a,b), axis=0)

print(c)

[[1 2]
 [3 4]
 [5 6]]


## Concaténation des colonnes

La concaténation des colonnes nécessite de transformer l'array `b` d'une matrice 1 x 2 vers une matrice 2 x 1.

L'axe est défini sur 1 pour ajouter la matrice transposée à l'array `a` en tant que nouvelle colonne.

**Exemple**



In [ ]:
# 2 x 2 matrix
a = np.array([[1, 2], [3, 4]])

# 1 x 2 matrix
b = np.array([[5,6]])

# adding a new column
# we must transpose the matrix b
c = np.concatenate((a,b.T), axis=1)

print(c)

[[1 2 5]
 [3 4 6]]


# Fractionnement d'un array

Le fractionnement est l'opposé de la concaténation.

La fractionnement de l'array est implémentée par les fonctions `numpy.split()`, `numpy.hsplit()` et `numpy.vsplit()`.

Pour chacune d'elles, on peut passer une liste d'indices donnant les points de fractionnement.

## Fractionner

**`numpy.split()`**

> Syntaxe
<font size = "4">
```python
numpy.split(ary, indices_or_sections, axis=0)
```
</font>

Fractionner un array en plusieurs sous-arrays en tant que vues dans `ary`.

*Paramètres*:
* `ary`: `ndarray`. Array à fractionner en sous-arrays.
* `indices_or_sections`: `int` ou array  1-D.
    * Si `indices_or_sections` est un entier, N, l'array sera fractionné en N arrays égaux le long de l'axe.
    * Si `indices_or_sections` est un array 1-D d'entiers triés, les entrées indiquent où le long de l'axe, l'array est fractionné.
* `axis`: `int`, facultatif. L'axe le long duquel fractionner, la valeur par défaut est 0.

*Retourne*:
* sub-Arrays: Liste de ndarrays. Une liste de sous-arrays comme vues dans `ary`.

**Exemple**



In [ ]:
arr = np.arange(10, 19)

arr1, arr2, arr3 = np.split(arr, 3)

print(arr)
print(arr1)
print(arr2)
print(arr3)

[10 11 12 13 14 15 16 17 18]
[10 11 12]
[13 14 15]
[16 17 18]


In [ ]:
arr = np.arange(10, 19)

arr1, arr2, arr3 = np.split(arr, [3,5])

print(arr)
print(arr1)
print(arr2)
print(arr3)

[10 11 12 13 14 15 16 17 18]
[10 11 12]
[13 14]
[15 16 17 18]


## Fractionnement vertical

**`numpy.vsplit()`**

> Syntaxe
<font size = "4">
```python
numpy.vsplit(ary, indices_or_sections)
```
</font>

Fractionner un array en plusieurs sous-arrays verticalement (au niveau de la ligne).

**Exemple**


In [ ]:
arr = np.arange(16).reshape((4, 4))

upper, lower = np.vsplit(arr, [2])

print(arr)
print(upper)
print(lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


## Fractionnement horizontal

**`numpy.hsplit()`**

> Syntaxe
<font size = "4">
```python
numpy.hsplit(ary, indices_or_sections)
```
</font>

Fractionner un array en plusieurs sous-arrays horizontalement (en colonne).

**Exemple**

In [ ]:
arr = np.arange(16).reshape((4, 4))

left, right = np.hsplit(arr, [2])

print(arr)
print(left)
print(right)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
