# Array concatenation and splitting

# Array concatenation

NumPy's concatenation function provides a method to join sequences of arrays along an existing axis.

If you need to build up a matrix from a set of smaller arrays, then use `numpy.concatenate()`.

> Syntax
<font size="4">
```python
numpy.concatenate((a1, a2, …), axis=0)
```
</font>

The `axis` parameter defines along wich axis or dimension the arrays should be joined. The default `axis=0` will join on the zero axis.

## Concatenation of rows

To concatenate two arrays `a` and `b` along the rows axis we set `axis=0`. This will add array `b` as a new row below array `a`.

**Example**



In [ ]:
import numpy as np

# 2 x 2 matrix
a = np.array([[1, 2], [3, 4]])

# 1 x 2 matrix
b = np.array([[5,6]])

# adding a new row
c = np.concatenate((a,b), axis=0)

print(c)

[[1 2]
 [3 4]
 [5 6]]


## Concatenation of columns

Concatenation of columns requires that we transpose array `b` from a 1 x 2 matrix to a 2 x 1 matrix.

The axis is set to 1 to add the transposed matrix to array `a` as a new column.

**Example**



In [ ]:
# 2 x 2 matrix
a = np.array([[1, 2], [3, 4]])

# 1 x 2 matrix
b = np.array([[5,6]])

# adding a new column
# we must transpose the matrix b
c = np.concatenate((a,b.T), axis=1)

print(c)

[[1 2 5]
 [3 4 6]]


# Array splitting

The opposite of concatenation is splitting.

Array splitting is implemented by the functions `numpy.split()`, `numpy.hsplit()` and `numpy.vsplit()`.

For each of these, we can pass a list of indices giving the split points.

## Split

**`numpy.split()`**

> Syntax
<font size="4">
```python
numpy.split(ary, indices_or_sections, axis=0)
```
</font>

Split an array into multiple sub-arrays as views into `ary`.

*Parameters*:
* `ary` : `ndarray`. Array to be divided into sub-arrays.
* `indices_or_sections` : `int` or 1-D array.
    * If `indices_or_sections` is an integer, N, the array will be divided into N equal arrays along axis.
    * If `indices_or_sections` is a 1-D array of sorted integers, the entries indicate where along axis the array is split.
* `axis` : `int`, optional. The axis along which to split, default is 0.

*Returns*:
* sub-arrays : list of ndarrays. A list of sub-arrays as views into `ary`.

**Example**



In [ ]:
arr = np.arange(10, 19)

arr1, arr2, arr3 = np.split(arr, 3)

print(arr)
print(arr1)
print(arr2)
print(arr3)

[10 11 12 13 14 15 16 17 18]
[10 11 12]
[13 14 15]
[16 17 18]


In [ ]:
arr = np.arange(10, 19)

arr1, arr2, arr3 = np.split(arr, [3,5])

print(arr)
print(arr1)
print(arr2)
print(arr3)

[10 11 12 13 14 15 16 17 18]
[10 11 12]
[13 14]
[15 16 17 18]


## Split vertically

**`numpy.vsplit()`**

> Syntax
<font size="4">
```python
numpy.vsplit(ary, indices_or_sections)
```
</font>

Split an array into multiple sub-arrays vertically (row-wise).

**Example**


In [ ]:
arr = np.arange(16).reshape((4, 4))

upper, lower = np.vsplit(arr, [2])

print(arr)
print(upper)
print(lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


## Split horizontally

**`numpy.hsplit()`**

> Syntax
<font size="4">
```python
numpy.hsplit(ary, indices_or_sections)
```
</font>

Split an array into multiple sub-arrays horizontally (column-wise).

**Example**

In [ ]:
arr = np.arange(16).reshape((4, 4))

left, right = np.hsplit(arr, [2])

print(arr)
print(left)
print(right)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
