<a href="https://colab.research.google.com/github/tariqzahratahdi/DataScience/blob/main/course_numpy_sorting_arrays_fr.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tri des arrays

Le tri des arrays de données est une tâche numérique très courante.

Ceci est facile à réaliser à l'aide de la fonction **`numpy.sort()`**.

## La méthode de tri

> Syntaxe
<font size = "4">
```python
numpy.sort(a, axis=-1, kind=None, order=None)
```
</font>

*Paramètres*
* `a`: l'array à trier.
* `axis`: `int` ou `None`, facultatif. L'axe sur lequel l'array sera trié. La valeur par défaut est `-1`, qui trie le long du dernier axe.
* `kind`: {`quicksort`, `mergesort`, `heapsort`, `stable`}, facultatif. L'algorithme de tri. La valeur par défaut est `quicksort`.

Le tri est effectué dans l'ordre croissant.


In [ ]:
import numpy as np

a = np.random.randint(10, 99, 9)
arr1 = a.reshape(3, 3)

print(arr1)

# sort
arr2 = np.sort(arr1)

print(arr2)

[[22 28 73]
 [60 62 90]
 [44 27 60]]
[[22 28 73]
 [60 62 90]
 [27 44 60]]


## Trier et aplatir

Pour aplatir l'array lors du tri, on ajoute `axis=None` à l'appel de tri.

In [ ]:
a = np.random.randint(10, 99, 9)
arr1 = a.reshape(3, 3)

print(arr1)

# sort and flatten array
arr2 = np.sort(arr1, axis=None)

print(arr2)

[[66 77 17]
 [86 20 77]
 [96 39 56]]
[17 20 39 56 66 77 77 86 96]


## Tri de chaque ligne

Pour trier chaque ligne d'un array 2D dans l'ordre croissant, on spécifie l'axe sur lequel trier. Dans ce cas, on doit trier le long de `axis=1`.

In [ ]:
a = np.random.randint(10, 99, 9)
arr1 = a.reshape(3, 3)

print(arr1)

# sort each row
arr2 = np.sort(arr1, axis=1)

print(arr2)

[[89 34 26]
 [48 70 16]
 [91 11 89]]
[[26 34 89]
 [16 48 70]
 [11 89 91]]


## Tri de chaque colonne

On procède de la même manière que le tri des lignes, sauf qu'on trie le long de `axis=0`.

In [ ]:
a = np.random.randint(10, 99, 9)
arr1 = a.reshape(3, 3)

print(arr1)

# trier chaque colonne
arr2 = np.sort(arr1, axis=0)

print(arr2)

[[81 59 25]
 [27 65 96]
 [44 57 92]]
[[27 57 25]
 [44 59 92]
 [81 65 96]]
