# Sorting arrays

Ordering or sorting arrays of data is a very common numerical task.

This is easy to complete when using the `numpy.sort()` function.

## The sort method

> Syntax
<font size="4">
```python
numpy.sort(a, axis=-1, kind=None, order=None)
```
</font>

*Parameters*
* `a` : the array to sort.
* `axis` : `int` or `None`, optional. The axis along which the array will be sorted. The default is `-1`, which sorts along the last axis.
* `kind` : {‘quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’}, optional. The sorting algorithm. The default is ‘quicksort’.

Sorting is performed in ascending order.


In [ ]:
import numpy as np

a = np.random.randint(10, 99, 9)
arr1 = a.reshape(3, 3)

print(arr1)

# sort
arr2 = np.sort(arr1)

print(arr2)

[[48 50 35]
 [25 53 33]
 [51 14 17]]
[[35 48 50]
 [25 33 53]
 [14 17 51]]


## Sort and flatten

To flatten the array when sorting add `axis=None` to the sort call.

In [ ]:
a = np.random.randint(10, 99, 9)
arr1 = a.reshape(3, 3)

print(arr1)

# sort and flatten array
arr2 = np.sort(arr1, axis=None)

print(arr2)

[[58 38 51]
 [39 69 13]
 [80 35 18]]
[13 18 35 38 39 51 58 69 80]


## Sort Each Row

To sort each row of a 2D array in ascending order you need to specify the axis along which to sort. In this case we need to sort along axis=1.

In [ ]:
a = np.random.randint(10, 99, 9)
arr1 = a.reshape(3, 3)

print(arr1)

# sort each row
arr2 = np.sort(arr1, axis=1)

print(arr2)

[[89 42 50]
 [86 29 80]
 [72 25 29]]
[[42 50 89]
 [29 80 86]
 [25 29 72]]


## Sort Each Column

This works in the same way as row sorting except that now you are sorting along axis=0.

In [ ]:
a = np.random.randint(10, 99, 9)
arr1 = a.reshape(3, 3)

print(arr1)

# sort each column
arr2 = np.sort(arr1, axis=0)

print(arr2)

[[81 59 25]
 [27 65 96]
 [44 57 92]]
[[27 57 25]
 [44 59 92]
 [81 65 96]]
